appproject:
  name: # Name for ArgoCD Project
  description:
  repositories:
    # - Repo name, must end with .git... https://github.com/kcsoukup/argocd-apps.git
  destinations:
    namespace: # Target namespace
    server: # in-cluster or https://kubernetes.default.svc

application:
  name: # Application Name
  source:
    repoURL: # Repo name, must end with .git... https://github.com/kcsoukup/argocd-apps.git
    path: # Directory name in Repo, use "." for main
    targetRevision: # HEAD or main or branch name
    helm:
      valueFiles:
        # Can be more than 1, ex: values.yaml for common, values-diffs.yaml for specifics
        # - values.yaml
  destination:
    server: # in-cluster or https://kubernetes.default.svc
    namespace: # Target namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: # 3
      backoff:
        duration: # "5s"
        factor: # 2
        maxDuration: # "3m"
