appproject:
  name: whatpod
  description: "WhatPod Application"
  repositories:
    - https://github.com/kcsoukup/argocd-apps.git
  destinations:
    namespace: mushroomhead
    server: https://kubernetes.default.svc

application:
  name: whatpod
  source:
    repoURL: https://github.com/kcsoukup/argocd-apps.git
    path: whatpod
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mushroomhead
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"
